source 'https://rubygems.org'
ruby '2.2.1'

gem 'rails', '~>4.1'
gem 'pg'
gem 'unicorn'
gem 'foreman'
gem 'paperclip'
gem 'protected_attributes'
gem 'activeadmin', github: 'activeadmin', ref: 'c6c43'
gem 'rmagick'
gem 'zencoder'
gem 'heroku-api'
gem 'roo'
gem 'secure_headers'
gem 'foreigner'
gem 'immigrant'
gem 'activerecord'
gem 'bcrypt'
gem 'stripe-rails'
gem 'sprockets'
gem 'font-awesome-rails'
gem 'instagram'
gem 'newrelic_rpm'
gem 'aws-sdk'
gem 'devise'
gem 'mail'
gem 'sendgrid'
gem 'premailer-rails'
gem 'nokogiri'

group :production do
  gem 'rails_12factor'
  gem 'rails_stdout_logging'
  gem 'dalli'
  gem 'memcachier'
  gem 'rails_serve_static_assets'
end
group :assets do
  gem 'jquery-rails'
  gem 'jquery-ui-rails'
  gem 'sass-rails'
  gem 'uglifier'
  gem 'compass-rails'
end
group :development do
  gem 'progress_bar'
  gem 'better_errors'
  gem 'binding_of_caller'
end
