S3_BUCKET: 'rijuice'
AWS_SECRET_ACCESS_KEY: '3AWdUuRrI96czHe5vgwWwQ6SkRUB8NTWjuhTGp2V'
AWS_ACCESS_KEY_ID: 'AKIAICJOIWCYQVWQW36A'

STRIPE_SECRET_KEY: 'sk_test_2jPsvi0qQfguqpV1SjkQOq84'
STRIPE_PUBLISHABLE_KEY: 'pk_test_BcvYOHT22B1zZQfF1VONpaHE'
